export default {
   USER_SIGNIN: "/customer/signin",
   USER_SIGNUP: "/customer/signup",
   VIEW_ALL_PRODUCT: "/product/viewproduct",
   SERACH_FILTER: "/product/search/",
   PRODUCT_BY_CATEGORY: "/product/products/",
   PRODUCT_BY_HOME_CATEGORY: "/product/products/",
   REMOVE_FROM_CART: "/cart/deleteproduct",
   VIEW_CART_ITEMS: "/cart/viewCartItems",
   ADD_TO_CART: "/cart/add-to-cart",
   PRODUCT_ADD: "/product/save",
   CUSTOMER_SAVE: "/customer/save",
   SELLER_SIGNIN: "/seller/signin",
   SELLER_SIGNUP: "/seller/signup",
   PRODUCT_LIST_BY_SELLER: "/product/productList",
   ORDER_BY_SELLER: "/order/getorderbyseller",
   UPDATE_PRODUCT: "/product/updated",
   VIEW_ALL_PRODUCT_ON_SCROLL: "/product/limitLoadproduct",
   CUSTOMER_SIGNIN: "/customer/customerSignin",
   VIEW_PRODUCT_BY_ID: "/product/",
   ORDERS_DETAILS:"/order/orderdetail",
   ADD_PRODUCT_REVIEW:"/product/addreview/reviews",
   PLACE_ORDER:"/order/buynow",
   RAZORPAY_MODE:"/api/razorpay",
   WISHLIST_DELETE:"/wishlist/delete",
   FEATURE_PRODUCT:"/product/featuresproduct",
   VIEW_WISHLIST:"/wishlist/viewwishlist",
   ADD_WISHLISTS:"/wishlist/addtowishlist"

}